name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  # Use a fallback github.run_id to avoid a syntax error.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Install Python dependencies
        run: make requirements.ci

      - name: Cache tox environments
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ matrix.python-version }}-${{ hashFiles('requirements/**') }}
