"""Generated by Django 4.2.16 on 2024-12-02 20:06."""

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    """
    Initial migration for the catalog plugin.

    Creates two models:
    - `AvailableCourse`: Represents available courses.
    - `Catalogue`: Represents a collection of courses.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, verbose_name='Course')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catalogue')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('courses', models.ManyToManyField(to='catalog_plugin.availablecourse', verbose_name='Available Courses')),
            ],
        ),
    ]
