# Generated by Django 3.2.17 on 2025-01-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_courseoverview_entrance_exam'),
        ('catalog_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcourses',
            options={'verbose_name_plural': 'Catalog Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='availablecourse',
            unique_together={('course',)},
        ),
    ]
