# Generated by Django 3.2.17 on 2025-04-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcourses',
            options={'verbose_name_plural': 'Catalog Courses'},
        ),
    ]
